### ISSUE TITLE
Celery's .delay() blocks the requests to api if the broker is down

### ISSUE THREAD

**Issue by Samy-33** [Velle-log/hs-api#26]

**Comment by sk364** [comment]
What do you mean by "freezes the API"?

**Comment by Samy-33** [comment]
Request times out, while api tries to connect to the broker blocking other requests.

**Comment by sk364** [comment]
I am gettting the HTTP response and am able to make further requests, except that the celery tasks are not executed (which do when I start the worker).

Please add steps on how to reproduce this issue.

**Comment by Samy-33** [comment]
Stop the **rabbitmq-server**  
 `$ sudo service rabbitmq-server stop`

**Comment by Samy-33** [comment]
@Velle-log/hs-api-ft [this](https://stackoverflow.com/questions/22233680/in-memory-broker-for-celery-unit-tests) may help. Will try this tonight.

**Comment by Samy-33** [comment]
Broker is supposed to ~be~ run in dev environment. If you don't want to run it, replace override **BROKER_BACKEND** in `dev.py` as 'memory'.
