### ISSUE TITLE
OPTIONS requests failing. Cors Issue

### ISSUE THREAD

**Issue by Samy-33** [Velle-log/hs-api#27]

**Comment by Samy-33** [comment]
@pranjulps3, this still the issue?

**Comment by sk364** [comment]
Looks like you approved #28

**Comment by Samy-33** [comment]
OPTIONS case is handled too?

**Comment by sk364** [comment]
That is by default handled by the library through [this](https://github.com/ottoyiu/django-cors-headers#cors_allow_methods) setting variable.

**Comment by Samy-33** [comment]
The issue was about OPTIONS getting `unauthorized` response.

**Comment by sk364** [comment]
Exactly, "was" :microphone: :droplet:
