### ISSUE TITLE
Redundant logs being displayed

### ISSUE THREAD

**Issue by Samy-33** [Velle-log/hs-api#29]
![Screenshot from 2019-07-28 12-38-10](https://user-images.githubusercontent.com/15676805/62003471-1c701000-b135-11e9-8f3f-0668b7fcbb4f.png)

**Comment by sk364** [comment]
Dev environment's platform independence can be achieved later. Seems like low priority to me.

**Comment by Samy-33** [comment]
We can take this up later. Just update `dev setup` wiki with workarounds to possible problems devs may face.

**Comment by sk364** [comment]
@Samy-33 still seeing redundant logs?

**Comment by Samy-33** [comment]
@sk364, once in a while.
![Screenshot from 2019-07-30 03-45-21](https://user-images.githubusercontent.com/15676805/62086671-c1493500-b27c-11e9-9fb3-2195e1a0eddd.png)
