### ISSUE TITLE
Modify signup logic based on new workflow

### ISSUE THREAD

**Issue by Samy-33** [Velle-log/hs-api#48]
New Sign Up flow

* Get user email -> verify if it exists ? move forward : prompt error.
* Get password and repeat password -> match password compliance ? send email and password to API to send OTP : prompt what's wrong.
* Take OTP -> verify it ? receive access token and authenticate : retry until retries end

**Comment by sk364** [comment]
@Velle-log/hs-api-ft  Can't we do step 1 and 2 together and save one API request?

**Comment by Samy-33** [comment]
We can do that but we have steppers in UI. I think it would be better if user knows about existing account in the first step when email is entered.  

Email and passwords are in separate stepper.

**Comment by sk364** [comment]
Is it not possible to move up a stepper without sending a request and getting a 20x status code?

**Comment by Samy-33** [comment]
It is possible. But my point was this:
> I think it would be better if user knows about existing account in the first step when email is entered.

**Comment by sk364** [comment]
This can result in a security breach for the registered users' email addresses.
That is why most systems still throw an error - `The username or password combination is wrong`, instead of `Username doesn't exist`.

But, it all depends on how much privacy the users in _our_ application want.

**Comment by Samy-33** [comment]
We'll strictly throttle this view for security reasons.
This view will not be used in login flow. Only signup flow.
