### ISSUE TITLE
Add endpoint to see if user with email exists

### ISSUE THREAD

**Issue by Samy-33** [Velle-log/hs-api#49]

**Comment by sk364** [comment]
@Velle-log/hs-api-ft Is it supposed to be a generic email checking view or there is only a particular action after checking the email, such as - sending OTP?

**Comment by Samy-33** [comment]
@sk364 it returns true or false, without triggering any other action.  
It would be better if we can make it generic, which accepts, email or username and checks if the user exists.

**Comment by sk364** [comment]
It seems to be a wasteful view, as there won't be many such views where we would need to check if the user exists before doing something. For the handful of views we have, we can check if the user exists along with the primary operation we need to do and send a `400` with a message saying that "User Does Not Exist.".

**Comment by Samy-33** [comment]
True. There won't be frequent request to such view but if user interface requires such kind of view then we have to provide this information.  

I am against using some other view having multiple purposes because in future, changes to that view might break this requirement. We'll have to remember thay this view serves two things. Telling user exists as well have other purposes that it serves.

**Comment by sk364** [comment]
I see you are aiming at even less cohesion. But, I think it's more than required.

Example:
Consider an API to fetch user profile using the user ID.
For this, there will be one view where it will first fetch the user associated with the user ID, which can result in 2 things:
1. User Exists -> Send Profile as response.
2. User Does Not Exist -> Send 404 as response.

According to you, we should divide this view into 2 views where one will check if the user exists or not and the other to send the profile with full confidence that the user will exist.

**Comment by Samy-33** [comment]
We can't assume that request will always contain parameters for which we will find a user.  
We can use other view whose purpose is very close to what we require (get user using email or username).  
We can use get user view for that but I suppose that only allows authenticated requests.

**Comment by sk364** [comment]
So, if we check the email first in a separate view, does it mean that the other views which need the email to exist won't check it such as Send OTP View or will it just send the OTP to whatever email it gets?

**Comment by Samy-33** [comment]
As far as I can see, checking user existence using `email` will be used only while signup, to let user know **An account with this email address already exists. Login?**  
All other views will validate if that email already exists, to be a source of truth in itself. It's just this particular endpoint is to help UI give better user experience, by not asking him for password before telling him that an account already exists with this email.
