### ISSUE TITLE
Send retry attempts left for OTP

### ISSUE THREAD

**Issue by Samy-33** [Velle-log/hs-api#50]

**Comment by sk364** [comment]
@Velle-log/hs-api-ft Do we need resends left as well in the response?

**Comment by Samy-33** [comment]
I don't think we need that. What do you think?

**Comment by sk364** [comment]
How will we hide/disable the `Resend` button on the client side, when there are attempts remaining, but no resends?

**Comment by Samy-33** [comment]
Once the user exceeds the resend limits, it'll received 403 error with resend exceeded message. Disable the button once we get that response.

**Comment by sk364** [comment]
Why can't we do the same for the attempts? Is it because we need to show him the number of attempts remaining?

**Comment by Samy-33** [comment]
Yes. Right.
