### ISSUE TITLE
Implement Signup Workflow

### ISSUE THREAD

**Issue by Samy-33** [Velle-log/hs-api#7]
SignUp workflow currently has following steps:
* User opens signup modal and enters `email` -> presses next.
* User is asked to enter the `OTP` sent to the entered email address.
* OTP is verified and then the `password` is set.
* After success of these steps, user is redirected to edit profile page, where it may or may not fill the details.

**Comment by Samy-33** [comment]
@Velle-log/hs-api-ft, we need an email sending API. Also, I suggest we send these email asynchronously to not overload the api.  
* We can use [celery](https://docs.celeryproject.org/en/latest/django/first-steps-with-django.html) for async tasks.  

Please do suggest any other alternative which may be better.

**Comment by sk364** [comment]
We can use Google SMTP server for mails.

Celery seems great. Easy setup with Django.
